// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/hello.proto
// Protobuf Java Version: 4.32.1

package io.github.mikeiansky.grpc;

@com.google.protobuf.Generated
public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
