/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_winson_jdkapi_jni_HelloJNIDemo */

#ifndef _Included_com_winson_jdkapi_jni_HelloJNIDemo
#define _Included_com_winson_jdkapi_jni_HelloJNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_winson_jdkapi_jni_HelloJNIDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_winson_jdkapi_jni_HelloJNIDemo_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
